#Parameters for our model for training
TrainingArguments:
  num_train_epochs: 10
  warmup_steps: 100
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  weight_decay: 0.01
  eval_steps: 500
  save_steps: 1000
  save_total_limit: 2