artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: Arsive/toxicity_classification_jigsaw
  local_data_file: artifacts/data_ingestion/data

data_validation:
  root_dir: artifacts/data_validation
  file_path: artifacts/data_ingestion/data
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data
  tokenizer_name: distilbert/distilbert-base-uncased