artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: Arsive/toxicity_classification_jigsaw
  local_data_file: artifacts/data_ingestion/data

data_validation:
  root_dir: artifacts/data_validation
  file_path: artifacts/data_ingestion/data
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data

model_trainer:
  root_dir: artifacts/model_trainer
  data_path_train: artifacts/data_transformation/train_transformed
  data_path_validation: artifacts/data_transformation/validation_transformed
  tokenizer_ckpt: distilbert/distilbert-base-uncased
  model_ckpt: distilbert/distilbert-base-uncased

prediction_pipeline:
  root_dir: artifacts/prediction_pipeline
  finetuned_model_path: artifacts\model_trainer\distilbert_full_finetuning_toxic_comments
  tokenizer_ckpt: distilbert/distilbert-base-uncased 